[build]
  publish = "dist"
  command = "npm run build:netlify"

[build.environment]
  GIT_LFS_ENABLED = "true"
  GIT_LFS_FETCH_METHOD = "custom"

[dev]
  command = "npm run dev"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html" 
  status = 200
