/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as CoachesRouteImport } from './routes/coaches'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as FacilitiesRouteImport } from './routes/facilities'
import { Route as ProgramsRouteImport } from './routes/programs'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TeamRouteImport } from './routes/team'
import { Route as TestimonialsRouteImport } from './routes/testimonials'
import { Route as TournamentsRouteImport } from './routes/tournaments'
import { Route as AboutMeetFounderRouteImport } from './routes/about/meet-founder'
import { Route as AboutOurStoryRouteImport } from './routes/about/our-story'
import { Route as BlogsIndexRouteImport } from './routes/blogs.index'
import { Route as BlogsSlugRouteImport } from './routes/blogs.$slug'
import { Route as CentresIndexRouteImport } from './routes/centres/index'
import { Route as CentresMajorDhyanChandSportsComplexRouteImport } from './routes/centres/major-dhyan-chand-sports-complex'
import { Route as CentresPunjabiBaghClubRouteImport } from './routes/centres/punjabi-bagh-club'
import { Route as CentresRoshanaraClubRouteImport } from './routes/centres/roshanara-club'
import { Route as InitiativesIndexRouteImport } from './routes/initiatives/index'
import { Route as InitiativesGlobalLearningRouteImport } from './routes/initiatives/global-learning'
import { Route as InitiativesSundayMatchPlayRouteImport } from './routes/initiatives/sunday-match-play'
import { Route as TeamSlugRouteImport } from './routes/team.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachesRoute = CoachesRouteImport.update({
  id: '/coaches',
  path: '/coaches',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FacilitiesRoute = FacilitiesRouteImport.update({
  id: '/facilities',
  path: '/facilities',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsRoute = ProgramsRouteImport.update({
  id: '/programs',
  path: '/programs',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const TestimonialsRoute = TestimonialsRouteImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () => rootRouteImport,
} as any)
const TournamentsRoute = TournamentsRouteImport.update({
  id: '/tournaments',
  path: '/tournaments',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutMeetFounderRoute = AboutMeetFounderRouteImport.update({
  id: '/meet-founder',
  path: '/meet-founder',
  getParentRoute: () => AboutRoute,
} as any)
const AboutOurStoryRoute = AboutOurStoryRouteImport.update({
  id: '/our-story',
  path: '/our-story',
  getParentRoute: () => AboutRoute,
} as any)
const BlogsIndexRoute = BlogsIndexRouteImport.update({
  id: '/blogs/',
  path: '/blogs/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogsSlugRoute = BlogsSlugRouteImport.update({
  id: '/blogs/$slug',
  path: '/blogs/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CentresIndexRoute = CentresIndexRouteImport.update({
  id: '/centres/',
  path: '/centres/',
  getParentRoute: () => rootRouteImport,
} as any)
const CentresMajorDhyanChandSportsComplexRoute =
  CentresMajorDhyanChandSportsComplexRouteImport.update({
    id: '/centres/major-dhyan-chand-sports-complex',
    path: '/centres/major-dhyan-chand-sports-complex',
    getParentRoute: () => rootRouteImport,
  } as any)
const CentresPunjabiBaghClubRoute = CentresPunjabiBaghClubRouteImport.update({
  id: '/centres/punjabi-bagh-club',
  path: '/centres/punjabi-bagh-club',
  getParentRoute: () => rootRouteImport,
} as any)
const CentresRoshanaraClubRoute = CentresRoshanaraClubRouteImport.update({
  id: '/centres/roshanara-club',
  path: '/centres/roshanara-club',
  getParentRoute: () => rootRouteImport,
} as any)
const InitiativesIndexRoute = InitiativesIndexRouteImport.update({
  id: '/initiatives/',
  path: '/initiatives/',
  getParentRoute: () => rootRouteImport,
} as any)
const InitiativesGlobalLearningRoute =
  InitiativesGlobalLearningRouteImport.update({
    id: '/initiatives/global-learning',
    path: '/initiatives/global-learning',
    getParentRoute: () => rootRouteImport,
  } as any)
const InitiativesSundayMatchPlayRoute =
  InitiativesSundayMatchPlayRouteImport.update({
    id: '/initiatives/sunday-match-play',
    path: '/initiatives/sunday-match-play',
    getParentRoute: () => rootRouteImport,
  } as any)
const TeamSlugRoute = TeamSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => TeamRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRouteWithChildren
  '/coaches': typeof CoachesRoute
  '/contact': typeof ContactRoute
  '/facilities': typeof FacilitiesRoute
  '/programs': typeof ProgramsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/team': typeof TeamRouteWithChildren
  '/testimonials': typeof TestimonialsRoute
  '/tournaments': typeof TournamentsRoute
  '/about/meet-founder': typeof AboutMeetFounderRoute
  '/about/our-story': typeof AboutOurStoryRoute
  '/blogs/$slug': typeof BlogsSlugRoute
  '/centres/major-dhyan-chand-sports-complex': typeof CentresMajorDhyanChandSportsComplexRoute
  '/centres/punjabi-bagh-club': typeof CentresPunjabiBaghClubRoute
  '/centres/roshanara-club': typeof CentresRoshanaraClubRoute
  '/initiatives/global-learning': typeof InitiativesGlobalLearningRoute
  '/initiatives/sunday-match-play': typeof InitiativesSundayMatchPlayRoute
  '/team/$slug': typeof TeamSlugRoute
  '/blogs/': typeof BlogsIndexRoute
  '/centres/': typeof CentresIndexRoute
  '/initiatives/': typeof InitiativesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRouteWithChildren
  '/coaches': typeof CoachesRoute
  '/contact': typeof ContactRoute
  '/facilities': typeof FacilitiesRoute
  '/programs': typeof ProgramsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/team': typeof TeamRouteWithChildren
  '/testimonials': typeof TestimonialsRoute
  '/tournaments': typeof TournamentsRoute
  '/about/meet-founder': typeof AboutMeetFounderRoute
  '/about/our-story': typeof AboutOurStoryRoute
  '/blogs/$slug': typeof BlogsSlugRoute
  '/centres/major-dhyan-chand-sports-complex': typeof CentresMajorDhyanChandSportsComplexRoute
  '/centres/punjabi-bagh-club': typeof CentresPunjabiBaghClubRoute
  '/centres/roshanara-club': typeof CentresRoshanaraClubRoute
  '/initiatives/global-learning': typeof InitiativesGlobalLearningRoute
  '/initiatives/sunday-match-play': typeof InitiativesSundayMatchPlayRoute
  '/team/$slug': typeof TeamSlugRoute
  '/blogs': typeof BlogsIndexRoute
  '/centres': typeof CentresIndexRoute
  '/initiatives': typeof InitiativesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRouteWithChildren
  '/coaches': typeof CoachesRoute
  '/contact': typeof ContactRoute
  '/facilities': typeof FacilitiesRoute
  '/programs': typeof ProgramsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/team': typeof TeamRouteWithChildren
  '/testimonials': typeof TestimonialsRoute
  '/tournaments': typeof TournamentsRoute
  '/about/meet-founder': typeof AboutMeetFounderRoute
  '/about/our-story': typeof AboutOurStoryRoute
  '/blogs/$slug': typeof BlogsSlugRoute
  '/centres/major-dhyan-chand-sports-complex': typeof CentresMajorDhyanChandSportsComplexRoute
  '/centres/punjabi-bagh-club': typeof CentresPunjabiBaghClubRoute
  '/centres/roshanara-club': typeof CentresRoshanaraClubRoute
  '/initiatives/global-learning': typeof InitiativesGlobalLearningRoute
  '/initiatives/sunday-match-play': typeof InitiativesSundayMatchPlayRoute
  '/team/$slug': typeof TeamSlugRoute
  '/blogs/': typeof BlogsIndexRoute
  '/centres/': typeof CentresIndexRoute
  '/initiatives/': typeof InitiativesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/coaches'
    | '/contact'
    | '/facilities'
    | '/programs'
    | '/sitemap.xml'
    | '/team'
    | '/testimonials'
    | '/tournaments'
    | '/about/meet-founder'
    | '/about/our-story'
    | '/blogs/$slug'
    | '/centres/major-dhyan-chand-sports-complex'
    | '/centres/punjabi-bagh-club'
    | '/centres/roshanara-club'
    | '/initiatives/global-learning'
    | '/initiatives/sunday-match-play'
    | '/team/$slug'
    | '/blogs/'
    | '/centres/'
    | '/initiatives/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/coaches'
    | '/contact'
    | '/facilities'
    | '/programs'
    | '/sitemap.xml'
    | '/team'
    | '/testimonials'
    | '/tournaments'
    | '/about/meet-founder'
    | '/about/our-story'
    | '/blogs/$slug'
    | '/centres/major-dhyan-chand-sports-complex'
    | '/centres/punjabi-bagh-club'
    | '/centres/roshanara-club'
    | '/initiatives/global-learning'
    | '/initiatives/sunday-match-play'
    | '/team/$slug'
    | '/blogs'
    | '/centres'
    | '/initiatives'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/coaches'
    | '/contact'
    | '/facilities'
    | '/programs'
    | '/sitemap.xml'
    | '/team'
    | '/testimonials'
    | '/tournaments'
    | '/about/meet-founder'
    | '/about/our-story'
    | '/blogs/$slug'
    | '/centres/major-dhyan-chand-sports-complex'
    | '/centres/punjabi-bagh-club'
    | '/centres/roshanara-club'
    | '/initiatives/global-learning'
    | '/initiatives/sunday-match-play'
    | '/team/$slug'
    | '/blogs/'
    | '/centres/'
    | '/initiatives/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRouteWithChildren
  CoachesRoute: typeof CoachesRoute
  ContactRoute: typeof ContactRoute
  FacilitiesRoute: typeof FacilitiesRoute
  ProgramsRoute: typeof ProgramsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TeamRoute: typeof TeamRouteWithChildren
  TestimonialsRoute: typeof TestimonialsRoute
  TournamentsRoute: typeof TournamentsRoute
  BlogsSlugRoute: typeof BlogsSlugRoute
  CentresMajorDhyanChandSportsComplexRoute: typeof CentresMajorDhyanChandSportsComplexRoute
  CentresPunjabiBaghClubRoute: typeof CentresPunjabiBaghClubRoute
  CentresRoshanaraClubRoute: typeof CentresRoshanaraClubRoute
  InitiativesGlobalLearningRoute: typeof InitiativesGlobalLearningRoute
  InitiativesSundayMatchPlayRoute: typeof InitiativesSundayMatchPlayRoute
  BlogsIndexRoute: typeof BlogsIndexRoute
  CentresIndexRoute: typeof CentresIndexRoute
  InitiativesIndexRoute: typeof InitiativesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coaches': {
      id: '/coaches'
      path: '/coaches'
      fullPath: '/coaches'
      preLoaderRoute: typeof CoachesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/facilities': {
      id: '/facilities'
      path: '/facilities'
      fullPath: '/facilities'
      preLoaderRoute: typeof FacilitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs': {
      id: '/programs'
      path: '/programs'
      fullPath: '/programs'
      preLoaderRoute: typeof ProgramsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/testimonials': {
      id: '/testimonials'
      path: '/testimonials'
      fullPath: '/testimonials'
      preLoaderRoute: typeof TestimonialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tournaments': {
      id: '/tournaments'
      path: '/tournaments'
      fullPath: '/tournaments'
      preLoaderRoute: typeof TournamentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/meet-founder': {
      id: '/about/meet-founder'
      path: '/meet-founder'
      fullPath: '/about/meet-founder'
      preLoaderRoute: typeof AboutMeetFounderRouteImport
      parentRoute: typeof AboutRoute
    }
    '/about/our-story': {
      id: '/about/our-story'
      path: '/our-story'
      fullPath: '/about/our-story'
      preLoaderRoute: typeof AboutOurStoryRouteImport
      parentRoute: typeof AboutRoute
    }
    '/blogs/': {
      id: '/blogs/'
      path: '/blogs'
      fullPath: '/blogs/'
      preLoaderRoute: typeof BlogsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs/$slug': {
      id: '/blogs/$slug'
      path: '/blogs/$slug'
      fullPath: '/blogs/$slug'
      preLoaderRoute: typeof BlogsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/centres/': {
      id: '/centres/'
      path: '/centres'
      fullPath: '/centres/'
      preLoaderRoute: typeof CentresIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/centres/major-dhyan-chand-sports-complex': {
      id: '/centres/major-dhyan-chand-sports-complex'
      path: '/centres/major-dhyan-chand-sports-complex'
      fullPath: '/centres/major-dhyan-chand-sports-complex'
      preLoaderRoute: typeof CentresMajorDhyanChandSportsComplexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/centres/punjabi-bagh-club': {
      id: '/centres/punjabi-bagh-club'
      path: '/centres/punjabi-bagh-club'
      fullPath: '/centres/punjabi-bagh-club'
      preLoaderRoute: typeof CentresPunjabiBaghClubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/centres/roshanara-club': {
      id: '/centres/roshanara-club'
      path: '/centres/roshanara-club'
      fullPath: '/centres/roshanara-club'
      preLoaderRoute: typeof CentresRoshanaraClubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/initiatives/': {
      id: '/initiatives/'
      path: '/initiatives'
      fullPath: '/initiatives/'
      preLoaderRoute: typeof InitiativesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/initiatives/global-learning': {
      id: '/initiatives/global-learning'
      path: '/initiatives/global-learning'
      fullPath: '/initiatives/global-learning'
      preLoaderRoute: typeof InitiativesGlobalLearningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/initiatives/sunday-match-play': {
      id: '/initiatives/sunday-match-play'
      path: '/initiatives/sunday-match-play'
      fullPath: '/initiatives/sunday-match-play'
      preLoaderRoute: typeof InitiativesSundayMatchPlayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team/$slug': {
      id: '/team/$slug'
      path: '/$slug'
      fullPath: '/team/$slug'
      preLoaderRoute: typeof TeamSlugRouteImport
      parentRoute: typeof TeamRoute
    }
  }
}

interface AboutRouteChildren {
  AboutMeetFounderRoute: typeof AboutMeetFounderRoute
  AboutOurStoryRoute: typeof AboutOurStoryRoute
}

const AboutRouteChildren: AboutRouteChildren = {
  AboutMeetFounderRoute: AboutMeetFounderRoute,
  AboutOurStoryRoute: AboutOurStoryRoute,
}

const AboutRouteWithChildren = AboutRoute._addFileChildren(AboutRouteChildren)

interface TeamRouteChildren {
  TeamSlugRoute: typeof TeamSlugRoute
}

const TeamRouteChildren: TeamRouteChildren = {
  TeamSlugRoute: TeamSlugRoute,
}

const TeamRouteWithChildren = TeamRoute._addFileChildren(TeamRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRouteWithChildren,
  CoachesRoute: CoachesRoute,
  ContactRoute: ContactRoute,
  FacilitiesRoute: FacilitiesRoute,
  ProgramsRoute: ProgramsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TeamRoute: TeamRouteWithChildren,
  TestimonialsRoute: TestimonialsRoute,
  TournamentsRoute: TournamentsRoute,
  BlogsSlugRoute: BlogsSlugRoute,
  CentresMajorDhyanChandSportsComplexRoute:
    CentresMajorDhyanChandSportsComplexRoute,
  CentresPunjabiBaghClubRoute: CentresPunjabiBaghClubRoute,
  CentresRoshanaraClubRoute: CentresRoshanaraClubRoute,
  InitiativesGlobalLearningRoute: InitiativesGlobalLearningRoute,
  InitiativesSundayMatchPlayRoute: InitiativesSundayMatchPlayRoute,
  BlogsIndexRoute: BlogsIndexRoute,
  CentresIndexRoute: CentresIndexRoute,
  InitiativesIndexRoute: InitiativesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
